myapp/coffee_voting/urls.py
from django.urls import path
from . import views

app_name = 'coffee_voting'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.Coffee_CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('<int:pk>/voting/', views.VotingView.as_view(), name='voting'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('coffee_voting/', include('coffee_voting.urls')),
    path('admin/', admin.site.urls),
    path('',  RedirectView.as_view(url='/coffee_voting/')),
]

myapp/coffee_voting/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator

class Roasting(models.Model):
    name=models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Coffee(models.Model):
    brand=models.CharField(max_length=255,verbose_name='豆の名前')
    roasting=models.ForeignKey(
        Roasting,
        on_delete=models.PROTECT,
        verbose_name='焙煎度'
    )
    beans_grams=models.FloatField(verbose_name='豆のグラム数 [g]')
    time=models.IntegerField(verbose_name='抽出時間 [s]')
    temperature=models.FloatField(verbose_name='湯の温度 [℃]')
    final_grams=models.FloatField(verbose_name='最終的な量 [ml]')
    comment=models.TextField(null=True,blank=True,verbose_name='抽出コメント')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.brand
    
    def get_absolute_url(self):
        return reverse('coffee_voting:detail', kwargs={'pk': self.pk})


class Voting(models.Model):
    bitterness=models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],verbose_name='苦味')
    sourness=models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],verbose_name='酸味')
    sweetness=models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],verbose_name='甘味')
    richness=models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],verbose_name='コク')
    flavor=models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],verbose_name='香り')
    review=models.TextField(max_length=255,null=True,blank=True,verbose_name='レビューコメント')
    coffee_id=models.ForeignKey(
        Coffee,
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.coffee_id)
    
    def get_absolute_url(self):
        return reverse('coffee_voting:index')

myapp/coffee_voting/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404,render
from .models import Coffee,Voting
from django.db.models import Avg


class IndexView(generic.ListView):
    model = Coffee

class DetailView(generic.DetailView):
    model = Coffee
    #レーダーチャート用の平均値データ取り出し
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        results_time=get_object_or_404(Coffee, pk=self.kwargs.get('pk')).time
        minutes=(results_time % 3600) // 60
        seconds=results_time % 60
        context["results_time"]="{}分{}秒".format(minutes, seconds)
        results=Voting.objects.filter(coffee_id=self.kwargs['pk'])
        bitterness_result=results.aggregate(Avg('bitterness'))
        context['bitterness_avg']=bitterness_result['bitterness__avg']
        sourness_result=results.aggregate(Avg('sourness'))
        context['sourness_avg'] =sourness_result['sourness__avg']
        sweetness_result=results.aggregate(Avg('sweetness'))
        context['sweetness_avg'] =sweetness_result['sweetness__avg']
        richness_result=results.aggregate(Avg('richness'))
        context['richness_avg'] =richness_result['richness__avg']
        flavor_result=results.aggregate(Avg('flavor'))
        context['flavor_avg'] =flavor_result['flavor__avg']
        context['reviews']=results.values_list('review', flat=True)
        return context

class Coffee_CreateView(generic.edit.CreateView):
    model = Coffee
    fields = '__all__'

class UpdateView(generic.edit.UpdateView):
    model = Coffee
    fields = '__all__'

class DeleteView(generic.edit.DeleteView):
    model = Coffee
    success_url = reverse_lazy('coffee_voting:index')
    
    def dispatch(self, request, *args, **kwargs):
        if request.POST:
            obj = request.POST['delete_pass']
            if obj!='goma': #入力された合言葉が正しいか判断(この場合の正解合言葉はgoma)
                context={
                    'coffee': get_object_or_404(Coffee, pk=self.kwargs.get('pk')),
                    'error_message':'あいことばが違います'
                }
                return render(self.request,'coffee_voting/coffee_confirm_delete.html',context)
            
        return super(DeleteView, self).dispatch(request, *args, **kwargs)

class VotingView(generic.edit.CreateView):
    model = Voting
    fields = ['bitterness','sourness','sweetness','richness','flavor','review']
    template_name="coffee_voting/coffee_voting.html"
    
    #対応するCoffee.idの自動格納
    def form_valid(self, form):
        table = get_object_or_404(Coffee, pk=self.kwargs.get('pk'))
        form.instance.coffee_id = table
        return super().form_valid(form)
    
    #投票画面に豆の名前を表示するためのデータ取り出し
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['coffee_name']=Coffee.objects.filter(pk=self.kwargs['pk']).first()
        return context

myapp/coffee_voting/templates/coffee_voting/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol:wght@700&family=Shippori+Mincho&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <style>
        body {
            background-color: rgb(207, 181, 135);
        }
        .navbar{
            font-family: 'Kaisei Decol', serif;
            background-color: rgb(182, 110, 9);
        }
        .canvas-container{
            width: 300px;
            height: 300px;
            margin-bottom: 100px;
        }
        canvas{
            background-color: white;
        }
        .btn{
	    border: 2px solid lightgray;
	    background-color: white;
            font-family: 'しっぽり明朝', serif;
            width: 50%;
            height: 60px;
        }
        .btn-delete{
	　　border: 2px solid lightgray;
	　　background-color: white;
        　　font-family: 'しっぽり明朝', serif;
        　　font-size: 98%;
        }
        .foot-link{
            font-size: 120%;
            padding: 15px;
        }
        h1{
            padding-top: 100px;
            font-family: 'しっぽり明朝', serif;
            border-bottom: 5px solid lightgray;
        }
        .review-title{
            font-size: clamp(18px, calc(100vw / 15), 50px);
        }
        h2{
            font-family: 'しっぽり明朝', serif;
            font-size: 180%;
            border-bottom: 5px solid lightgray;
            padding-top: 30px;
        }
        table{
            font-size: 80%;
            background-color: rgb(193, 189, 184);
        }
        div{
            font-size: 108%;
        }
        li{
            font-size: 108%;
        }
        .error-message{
            color: red;
            padding-top: 1%;
            font-size: 110%;
        }
        .review-content{
            font-size: 85%;
        }
    </style>
    <title>珈琲評価システム</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class='navbar-brand' href='{% url "coffee_voting:index" %}'>珈琲評価システム</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href='{% url "coffee_voting:create" %}'>新規珈琲登録</a></li>
                    <li><a href='https://forms.gle/dXPyhRfK1EF31QFv7'>ご意見フォーム</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class='container'>
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

myapp/coffee_voting/templates/coffee_voting/coffee_confirm_delete.html
{% extends './base.html' %}
{% block content %}

<h1>珈琲情報の削除</h1>
<p>'{{ coffee.brand }}'を削除しますか?</p>
<form action='' method='post'>{% csrf_token %}
    あいことば：<input type='text' name='delete_pass'>
    <button  type='submit' class='btn-delete'>削除する</button>
</form>
{% if error_message %}
    <p class=error-message>⚠エラー：{{error_message}}</p>
{% endif %}
<div class=foot-link>
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

myapp/coffee_voting/templates/coffee_voting/coffee_detail.html
{% extends './base.html' %}
{% block content %}

<h1>詳細情報</h1>
<div>
    <h2>抽出条件</h2>
    <p>豆の名前：{{ coffee.brand }}</p>
    <p>焙煎度：{{ coffee.roasting }}</p>
    <p>豆の重量：{{ coffee.beans_grams }} g</p>
    <p>抽出時間：{{ results_time }}</p>
    <p>湯の温度：{{ coffee.temperature }} ℃</p>
    <p>最終的な量：{{ coffee.final_grams }} ml</p>
    {% if coffee.comment %}
        <p>【抽出コメント】</p>
        <p>{{ coffee.comment |linebreaksbr}}</p>
    {% endif %}
</div>
<div class="canvas-container">
    <h2>レビューの平均値</h2>
    <canvas id="radar-chart"></canvas>

    <script type="text/javascript">
    /* idが"radar-chart"の要素を取得 */
    var ctx = document.getElementById("radar-chart");
    
    /* 上記要素にチャートを描画　*/
    var myRadarChart = new Chart(ctx, {
        type: 'radar',
        data: {
            labels: ['苦味', '酸味', '甘み', 'コク', '香り'],
            datasets: [{
                label: "平均値",
                data: [
                '{{bitterness_avg}}','{{sourness_avg}}','{{sweetness_avg}}','{{richness_avg}}','{{flavor_avg}}'],
            }]},
        options: {
            scale: {
                r: {
                    min: 0,
                    max: 5,
                    ticks: {
                        stepSize: 1
                    }
                }
            }
        }
    });
    </script>
</div>
<div>
    {% if reviews %}
        <h2>レビューコメント</h2>
        {% for review in reviews %}
            {% if review %}
                <li class="review-content">{{review}}</li>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
<div class=foot-link>
    <a href='{% url "coffee_voting:index" %}'>一覧</a> |
    <a href='{% url "coffee_voting:update" coffee.pk %}'>編集</a> |
    <a href='{% url "coffee_voting:voting" coffee.pk %}'>レビュー</a> |
    <a href='{% url "coffee_voting:delete" coffee.pk %}'>削除</a> |
</div>

{% endblock %}

myapp/coffee_voting/templates/coffee_voting/coffee_form.html
{% extends './base.html' %}
{% block content %}

<h1>珈琲情報の{{ object|yesno:'更新,作成'}}</h1>
<ul>
    <li>数字は半角で入力してください</li>
    <li>その他抽出の際に意識した点、豆の追加情報などがあれば「抽出コメント」欄に書いてください(なくても全然OKです)</li>
    <li>アイスコーヒーの場合は、その旨を「抽出コメント」欄に書いてもらえると嬉しいです</li>
</ul>

<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }} <!--全ての項目を表示-->
    <button type='submit' class='submit'>{{ object|yesno:'更新,作成'}}</button>
</form>
<div class=foot-link>
    <!--JavaScriptの呼び出しで、前のページに戻る機能を実現-->
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

myapp/coffee_voting/templates/coffee_voting/coffee_list.html
{% extends './base.html' %}
{% block content %}
    <h1>珈琲一覧(新しい順)</h1>
    <table class='table table-striped table-hover'>
        <tr>
            <th>抽出日時(年/月/日 時)</th><th>豆の名前</th><th>抽出情報詳細</th><th>レビュー画面へ</th>
        </tr>
        {% for coffee in object_list reversed %}
        <tr>
            <td>{{ coffee.created_at|date:"Y/m/d H:i" }}</td>
            <td>{{ coffee.brand }}</td>
            <td><a href='{% url "coffee_voting:detail" coffee.pk %}'>詳細</a></td>
            <td><a href='{% url "coffee_voting:voting" coffee.pk %}'>レビュー</a></td>
        </tr>
        {% endfor %}
    </table>
    
    <div class=foot-link>
        <a href='{% url "coffee_voting:create" %}'>新規珈琲登録</a>
    </div>
{% endblock %}

myapp/coffee_voting/templates/coffee_voting/coffee_voting.html
{% extends './base.html' %}
{% block content %}

<h1 class=review-title>レビュー[{{coffee_name.brand}}]</h1>
<ul>
    <li>各項目を1~5の5段階で評価してください</li>
    <li>その他コメントがあれば「レビューコメント」欄に書いてくださいね(なくても全然OKです)</li>
</ul>
<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }} <!--全ての項目を表示-->
    <button  type='submit' class='btn btn-dark'>投稿</button>
</form>
<div class=foot-link>
    <!--JavaScriptの呼び出しで、前のページに戻る機能を実現-->
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}